services:
  web:
    container_name: ruby_web
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
    - 3000:3000
    expose: [3000]
    command: >
      sh script/web-container-startup.sh
    volumes:
      - ./:/app
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      static-network:
        ipv4_address: 172.21.128.1
    environment:
      DB_USER: root
      DB_PASSWORD: testtest
      DB_NAME: hello_world
      DB_HOST: mysql
      RAILS_ENV: development
      ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: zBP9hnKrrH3aFJ2QUl2RUaylcNISCEnQ
      ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: CXZphBAzszhEcU2w8YtYDkIta5SRpVMA
      ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: LECZczsUN1nu9YjWOqf96U9lObxf8cuj

  mysql:
    image: mysql:9.2
    container_name: ruby_db
    volumes:
      # - /tmp/mysql/:/var/lib/mysql # This causes an issue on Mac M1 chips
      - docker-mysql-data:/var/lib/mysql
      - ./script/db-container-startup.sh:/script/db-container-startup.sh
    ports:
      - 3306:3306
    expose: [3306]
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: testtest
    command: >
      sh script/db-container-startup.sh
    networks:
      static-network:
        ipv4_address: 172.21.128.2

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    container_name: ruby_phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_HOST: 172.21.128.2
      PMA_USER: root
      PMA_PASSWORD: testtest
    depends_on:
      - mysql
    networks:
      static-network:
        ipv4_address: 172.21.128.3

volumes:
  docker-mysql-data:

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.21.0.0/16